<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends EntityRepository {
    
    public function ListaDql($nombre = "") {        
        $dql  = "SELECT g FROM AppBundle:Grupo g WHERE g.codigoGrupoPk <> 0 ";
        if($nombre != "" ) {
            $dql .= " AND g.nombre LIKE '%" . $nombre . "%'";
        }        
        $dql .= " ORDER BY g.nombre";
        return $dql;
    }
}