<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitanteRepository extends EntityRepository {
    
    public function ListaDql($codigoGrupo = "", $identificacion = "", $nombre = "") {        
        $dql  = "SELECT v FROM AppBundle:Visitante v WHERE v.codigoVisitantePk <> 0 ";
        if($nombre != "" ) {
            $dql .= " AND v.nombre LIKE '%" . $nombre . "%'";
        }
        if($identificacion != "" ) {
            $dql .= " AND v.numeroIdentificacion LIKE '%" . $identificacion . "%'";
        }         
        if($codigoGrupo != "" ) {
            $dql .= " AND v.codigoGrupoFk = " . $codigoGrupo;
        }        
        $dql .= " ORDER BY v.nombre";
        return $dql;
    }
}