# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
                

    firewalls:
        #No tocar por aqui no entra
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false          

        default:
            pattern: /.*
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login    
            logout:
                path:   /logout
                target: /                
            anonymous: ~                
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN } 
        - { path: ^/*, roles: ROLE_USER } 
